-- Insert sample security events (50 events with UUID generation)
INSERT INTO security_logs (event_type, ip_address, username, action, user_agent, threat_level, threat_score, blocked, reason, sensor_id, source, metadata) VALUES
('brute_force_ssh', '192.168.1.100', 'admin', 'login_attempt', 'Mozilla/5.0', 'critical', 95, true, 'Multiple failed SSH logins', 'sensor-01', 'ssh_log', '{}'),
('sql_injection', '10.0.0.5', 'webapp', 'query', 'SQLMap/1.0', 'critical', 98, true, 'SQL injection attempt', 'sensor-02', 'web_firewall', '{}'),
('privilege_escalation', '172.16.0.50', 'user123', 'sudo_cmd', 'bash', 'critical', 92, true, 'Privilege escalation', 'sensor-01', 'auditd', '{}'),
('port_scan', '203.0.113.45', NULL, 'network_probe', 'nmap', 'high', 78, true, 'Network scan', 'sensor-03', 'ids', '{}'),
('suspicious_login', '198.51.100.22', 'john_doe', 'login', 'curl', 'high', 75, false, 'Unusual location', 'sensor-02', 'auth_log', '{}'),
('malware_detection', '192.168.2.15', 'user456', 'download', 'Firefox', 'high', 85, true, 'Malware file', 'sensor-01', 'antivirus', '{}'),
('ddos_attempt', '192.0.2.100', NULL, 'flood', 'HTTP', 'high', 82, true, 'DDoS flood', 'sensor-03', 'ids', '{}'),
('phishing_email', '203.0.113.88', NULL, 'email', 'Thunderbird', 'high', 73, false, 'Phishing detected', 'sensor-02', 'email_gateway', '{}'),
('failed_login', '192.168.1.50', 'bob_smith', 'login', 'ssh', 'medium', 45, false, 'Failed login', 'sensor-01', 'ssh_log', '{}'),
('failed_login', '10.0.0.100', 'alice_wonder', 'login', 'ssh', 'medium', 42, false, 'Failed login', 'sensor-02', 'ssh_log', '{}'),
('unusual_traffic', '172.16.0.75', NULL, 'data_transfer', 'HTTP', 'medium', 55, false, 'Unusual traffic', 'sensor-03', 'netflow', '{}'),
('file_access', '192.168.1.120', 'user789', 'read', 'bash', 'medium', 50, false, 'Sensitive file', 'sensor-01', 'file_integrity', '{}'),
('weak_password', '10.0.0.55', 'new_user', 'create', 'web_ui', 'medium', 35, false, 'Weak password', 'sensor-02', 'ldap', '{}'),
('cert_expiry', '192.168.2.50', NULL, 'check', 'openssl', 'medium', 40, false, 'Cert expiring', 'sensor-01', 'cert_monitor', '{}'),
('unauthorized_access', '172.16.0.120', 'guest', 'access', 'browser', 'medium', 58, false, 'Unauthorized access', 'sensor-03', 'web_server', '{}'),
('suspicious_process', '192.168.1.200', 'system', 'exec', 'powershell', 'medium', 52, false, 'Suspicious process', 'sensor-02', 'edr', '{}'),
('policy_violation', '10.0.0.200', 'contractor', 'usb', 'device', 'medium', 48, true, 'USB blocked', 'sensor-01', 'dlp', '{}'),
('failed_api_auth', '192.168.2.80', 'service', 'api', 'curl', 'medium', 38, false, 'Failed auth', 'sensor-03', 'api_log', '{}'),
('config_change', '192.168.1.50', 'admin', 'firewall', 'web_ui', 'low', 20, false, 'Rule modified', 'sensor-01', 'syslog', '{}'),
('user_enum', '10.0.0.75', NULL, 'ldap_query', 'search', 'low', 15, false, 'User enumeration', 'sensor-02', 'directory', '{}'),
('port_open', '172.16.0.100', NULL, 'service', 'systemd', 'low', 25, false, 'Port open', 'sensor-01', 'ids', '{}'),
('failed_login', '192.168.1.75', 'bob', 'login', 'ssh', 'low', 10, false, 'Failed login', 'sensor-03', 'ssh_log', '{}'),
('info_access', '10.0.0.150', 'analyst', 'view', 'web_ui', 'info', 5, false, 'Info access', 'sensor-02', 'audit', '{}'),
('patch_available', '192.168.2.100', NULL, 'check', 'manager', 'low', 8, false, 'Patch available', 'sensor-01', 'patch', '{}'),
('failed_login', '172.16.0.150', 'test', 'login', 'web_ui', 'low', 12, false, 'Failed login', 'sensor-02', 'auth_log', '{}'),
('backup_ok', '192.168.1.100', 'backup', 'backup', 'service', 'info', 0, false, 'Backup done', 'sensor-01', 'backup_log', '{}'),
('audit_pass', '10.0.0.100', 'auditor', 'review', 'tool', 'info', 0, false, 'Audit passed', 'sensor-03', 'audit_log', '{}'),
('failed_login', '192.168.2.120', 'user', 'login', 'ssh', 'low', 11, false, 'Failed login', 'sensor-02', 'ssh_log', '{}'),
('brute_force', '203.0.113.200', 'root', 'login', 'ssh', 'critical', 94, true, 'SSH brute force', 'sensor-01', 'ssh_log', '{}'),
('malware', '192.168.1.88', 'infected', 'download', 'chrome', 'high', 88, true, 'Ransomware detected', 'sensor-03', 'antivirus', '{}'),
('failed_login', '10.0.0.200', 'temp', 'login', 'rdp', 'low', 13, false, 'Failed login', 'sensor-01', 'rdp_log', '{}'),
('suspicious_login', '172.16.0.200', 'vip', 'login', 'vpn', 'high', 76, false, 'Suspicious login', 'sensor-02', 'vpn_log', '{}'),
('data_leak', '192.168.2.200', 'insider', 'email', 'outlook', 'critical', 99, true, 'Data exfil', 'sensor-01', 'dlp', '{}'),
('ddos', '198.51.100.50', NULL, 'flood', 'TCP', 'high', 81, true, 'DDoS attack', 'sensor-03', 'ids', '{}'),
('failed_login', '192.168.1.150', 'user', 'login', 'ssh', 'low', 9, false, 'Failed login', 'sensor-02', 'ssh_log', '{}'),
('policy_vio', '10.0.0.180', 'manager', 'usb', 'device', 'medium', 50, true, 'USB blocked', 'sensor-01', 'dlp', '{}'),
('failed_login', '172.16.0.180', 'junior', 'login', 'ssh', 'low', 10, false, 'Failed login', 'sensor-03', 'ssh_log', '{}'),
('suspicious_proc', '192.168.2.150', 'user999', 'exec', 'cmd', 'medium', 54, false, 'Suspicious process', 'sensor-02', 'edr', '{}'),
('bad_cert', '10.0.0.250', NULL, 'check', 'openssl', 'low', 7, false, 'Invalid cert', 'sensor-01', 'ssl', '{}'),
('failed_login', '192.168.1.175', 'demo', 'login', 'web_ui', 'low', 8, false, 'Failed login', 'sensor-02', 'auth_log', '{}'),
('port_scan', '203.0.113.100', NULL, 'probe', 'nmap', 'high', 79, true, 'Port scan', 'sensor-03', 'ids', '{}'),
('failed_login', '172.16.0.175', 'guest', 'login', 'rdp', 'low', 9, false, 'Failed login', 'sensor-01', 'rdp_log', '{}'),
('susp_login', '192.168.2.175', 'exec', 'login', 'portal', 'high', 74, false, 'Suspicious login', 'sensor-02', 'auth_log', '{}'),
('malware', '10.0.0.125', 'machine', 'scan', 'antivirus', 'high', 86, true, 'Botnet malware', 'sensor-01', 'antivirus', '{}'),
('failed_api', '192.168.1.225', 'service', 'api', 'curl', 'low', 11, false, 'Failed API', 'sensor-03', 'api_log', '{}'),
('unusual_traffic', '172.16.0.225', NULL, 'transfer', 'TCP', 'medium', 56, false, 'Unusual traffic', 'sensor-02', 'netflow', '{}'),
('failed_login', '10.0.0.225', 'legacy', 'login', 'ssh', 'low', 10, false, 'Failed login', 'sensor-01', 'ssh_log', '{}'),
('priv_esc', '192.168.2.225', 'user', 'sudo', 'bash', 'critical', 91, true, 'Priv escalation', 'sensor-02', 'auditd', '{}'),
('failed_login', '172.16.0.225', 'worker', 'login', 'vpn', 'low', 9, false, 'Failed login', 'sensor-03', 'vpn_log', '{}'),
('ddos', '203.0.113.150', NULL, 'flood', 'HTTP', 'high', 80, true, 'HTTP DDoS', 'sensor-01', 'ids', '{}');

-- Insert sample alerts
INSERT INTO alerts (title, severity, ip_address, username, description, status) VALUES
('Critical SSH Brute Force', 'critical', '192.168.1.100', 'admin', 'Multiple failed SSH attempts', 'open'),
('SQL Injection Attack', 'critical', '10.0.0.5', NULL, 'SQL injection blocked', 'open'),
('Privilege Escalation', 'critical', '172.16.0.50', 'user123', 'Unauthorized escalation', 'open'),
('Port Scan Detected', 'high', '203.0.113.45', NULL, 'Network reconnaissance', 'open'),
('Suspicious Login Location', 'high', '198.51.100.22', 'john_doe', 'Login from unusual location', 'acknowledged'),
('Malware File', 'high', '192.168.2.15', 'user456', 'Trojan detected', 'open'),
('DDoS Attack', 'high', '192.0.2.100', NULL, 'Distributed attack in progress', 'open'),
('Phishing Email', 'high', '203.0.113.88', NULL, 'Malicious email detected', 'acknowledged'),
('Data Exfiltration', 'critical', '192.168.2.200', 'insider', 'Sensitive data transfer blocked', 'open'),
('Ransomware Detected', 'high', '192.168.1.88', 'infected', 'Ransomware signature match', 'open');
